spring:
  application:
    name: SpringBootRest
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/xe
    driverClassName: oracle.jdbc.OracleDriver
    username: system
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
server:
  port: 9090